# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d083833126b9041bd39badf3572b10347c551cc49677a3e14b65b534ba3de7374a47ae04ea7806156cd69e2c60f19336446ffee37c7d91bd93052ae0ae2e5bab

test:
  secret_key_base: 0c3751fea379a704d8f3f262b1f01534b07b44ad3a7f4d7fdde3546261a29e89d758d8e1593f682ee7fec7c41bf5c7082c73fa6167b4039ad813e95fddd54242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
